# Copyright 2024 Defense Unicorns
# SPDX-License-Identifier: AGPL-3.0-or-later OR LicenseRef-Defense-Unicorns-Commercial

# No upstream chart

# Example

# image:
#   repository: ghcr.io/roboturnerdev/excalidraw
#   digest: "sha256:<flavor specific digest>"