image:
  repository: docker.io/excalidraw/excalidraw
  digest: ""
  pullPolicy: IfNotPresent

serviceAccount:
  create: true
  name: ""

podLabels:
  app.kubernetes.io/name: excalidraw


readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 10

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 15
  periodSeconds: 20